spring:
  application:
    name: new
  cloud:
    config:
      uri: http://localhost:8888
  profiles:
    active: default
server:
  port: 8082

my:
  name: premji

management:
  endpoints:
    web:
      exposure:
        include: "*"
